version: '3.3'

services:
  nginx:
    image: nginx:alpine
    container_name: archimedes-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/stereosonic/data/archimedes.txt:/usr/share/nginx/html/archimedes.txt
    restart: unless-stopped
