version: '3.3'

services:
  archimedes:
    image: nginx:alpine
    container_name: archimedes
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # mount your text file into the container
      - /home/stereosonic/data/archimedes.txt:/data/archimedes.txt:ro
      # mount the custom nginx config
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
